version: '3'
services:

  bullet:
    image: nasoym/bullet_container
    volumes:
      - ./examples:/pybullet_examples
    tty: true
    ports:
      - 8765:8765
    command: python3 /pybullet_examples/pybullet_server.py

